const categories = {
  daParliament: ['ANC', 'DA', 'EFF', 'IFP', 'FFPlus', 'ActionSA', 'ATM'],
  daKitchen: [
    'Nando’s',
    'Steers',
    'McDonalds',
    'KFC',
    'Debonairs',
    'Wimpy',
    'Fishaways',
    'Kota Joe',
  ],
  daDressingRoom: [
    'MR Price',
    'Identity',
    'Edgar’s',
    'Markharm',
    'Legit',
    'Truworths',
    'Foschini',
  ],
  daGarrage: [
    'BMW',
    'Audi',
    'Mercedes Benz',
    'Jaguar',
    'Range Rover',
    'VW',
    ' Ford',
  ],
  daMarket: [
    'Woolworths',
    'Food Market',
    'Checkers',
    'Shoprite',
    'PnP',
    'Food Lovers',
    'Spar',
    'Boxer',
    'Cambridge',
  ],
}
